# Rubocop config to keep in line with our changes to the style guide
Encoding:
  Enabled: false

LineLength:
  Max: 200

CommentAnnotation:
  Enabled: false

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/MethodLength:
  Max: 20

Lint/UnusedMethodArgument:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/rack-request-id-passthrough.rb"

Style/DoubleNegation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
